export * from './guards'
export * from './status'
export * from './render'

import {
  isVideoTimelineItem,
  isImageTimelineItem,
  isAudioTimelineItem,
  isTextTimelineItem,
  hasVisualProperties,
  hasAudioProperties,
  supportsClipTransitionOut,
  supportsClipFilter,
} from './guards'
import {
  isReady,
  isLoading,
  hasError,
  canEdit,
  getStatusText,
  getProgressInfo,
  getErrorInfo,
} from './status'
import {
  getBaseRenderConfig,
  getBaseVisualConfig,
  getBaseAudioConfig,
  getBaseTextConfig,
  getBaseExtraRenderConfig,
  getMergedExtraRenderConfig,
  getBaseTransition,
  getBaseFilter,
  getBaseMask,
  getMergedRenderConfig,
  getResolvedTransition,
  getResolvedFilter,
  getResolvedMask,
  getResolvedRenderConfig,
} from './render'

export const TimelineItemQueries = {
  isVideoTimelineItem,
  isImageTimelineItem,
  isAudioTimelineItem,
  isTextTimelineItem,
  hasVisualProperties,
  hasAudioProperties,
  supportsClipTransitionOut,
  supportsClipFilter,
  isReady,
  isLoading,
  hasError,
  canEdit,
  getStatusText,
  getProgressInfo,
  getErrorInfo,
  getBaseRenderConfig,
  getBaseVisualConfig,
  getBaseAudioConfig,
  getBaseTextConfig,
  getBaseExtraRenderConfig,
  getMergedExtraRenderConfig,
  getBaseTransition,
  getBaseFilter,
  getBaseMask,
  getMergedRenderConfig,
  getResolvedTransition,
  getResolvedFilter,
  getResolvedMask,
  getResolvedRenderConfig,
}
