export * from './guards'
export * from './status'
export * from './render'

import {
  isVideoTimelineItem,
  isImageTimelineItem,
  isAudioTimelineItem,
  isTextTimelineItem,
  hasVisualProperties,
  hasAudioProperties,
  supportsClipTransitionOut,
  supportsClipFilter,
} from './guards'
import {
  isReady,
  isLoading,
  hasError,
  canEdit,
  getStatusText,
  getProgressInfo,
  getErrorInfo,
} from './status'
import {
  getBaseRenderConfig,
  getVisualRenderConfig,
  getAudioRenderConfig,
  getTextRenderConfig,
  patchVisualRenderConfig,
  patchAudioRenderConfig,
  patchTextRenderConfig,
  getExtraRenderConfig,
  getRenderExtraRenderConfig,
  getTransition,
  getRenderTransition,
  getFilter,
  getMask,
  getRenderFilter,
  getRenderMask,
  getRenderConfig,
} from './render'

export const TimelineItemQueries = {
  isVideoTimelineItem,
  isImageTimelineItem,
  isAudioTimelineItem,
  isTextTimelineItem,
  hasVisualProperties,
  hasAudioProperties,
  supportsClipTransitionOut,
  supportsClipFilter,
  isReady,
  isLoading,
  hasError,
  canEdit,
  getStatusText,
  getProgressInfo,
  getErrorInfo,
  getBaseRenderConfig,
  getVisualRenderConfig,
  getAudioRenderConfig,
  getTextRenderConfig,
  patchVisualRenderConfig,
  patchAudioRenderConfig,
  patchTextRenderConfig,
  getExtraRenderConfig,
  getRenderExtraRenderConfig,
  getTransition,
  getRenderTransition,
  getFilter,
  getMask,
  getRenderFilter,
  getRenderMask,
  getRenderConfig,
}
